### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-jetpack#161]
Refresh the screen when the template changes in the server

**Comment by nelson-glauber** [comment]
This is how it is implemented in SwiftUI
https://github.com/liveview-native/liveview-client-swiftui/blob/f16ace9a37102caed77dc5ddfb223c7eecd47d07/Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift#L322
