### ISSUE TITLE
Stylesheet support for modifiers

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/liveview-client-jetpack#179]
LiveView Native now has the concept of stylesheets. These were built for SwiftUI modifiers and similar systems (such as Compose modifiers).

Stylesheets are compiled to an AST format and sent to the client via `<compiled-lvn-stylesheet>` elements. The classes sent by these elements are merged into a stylesheet as we continue down the tree.

```html
<compiled-lvn-stylesheet body="%{...}">
  ...
</compiled-lvn-stylesheet>
```

You can see more at [`live_view_native_stylesheet`](https://github.com/liveview-native/live_view_native_stylesheet), including details about the AST format. The basic format is:

```
{<name>, [<meta>], [<args>, [<named args>]]}
```

As an example, here is how one set of modifiers in Compose could be converted to a stylesheet:

```kt
Column(
    Modifier
        .clickable(onClick = onClick)
        .padding(16.dp)
        .fillMaxWidth()
) {
    // rest of the implementation
}
```

```html
<Column class="my-card-class">
  <!-- rest of the implementation -->
</Column>
```
```elixir
"my-card-class" do
  clickable(onClick = event("my-click-handler"))
  padding(16.dp)
  fillMaxWidth()
end
```

The rules parser can be customized per-platform. It would probably be easiest to start from the [SwiftUI client's rules parser](https://github.com/liveview-native/liveview-client-swiftui/tree/main/lib/live_view_native/swiftui/rules_parser) and make some tweaks for Kotlin-like syntax. For example, changing labelled arguments to use `<argument> = <value>` instead of `<argument>: <value>`. The AST format would remain the same.

**Comment by bcardarella** [comment]
For this set of rules:

```elixir
"my-card-class" do
  clickable(onClick = event("my-click-handler"))
  padding(16.dp)
  fillMaxWidth()
end
```

we could have this AST:

```elixir
%{
  "my-card-class" => [
    {:clickable, [], [{:=, [], [:onClick, {:__event__, [], ["my-click-hadler"]}]}],
    {:padding, [], [{:., [], [16, :dp]}]},
    {:fillMaxWidth, [], []}
  ]
}
```

**Comment by nelson-glauber** [comment]
I'm going to investigate an approach using [ANTLR](https://www.antlr.org/) in order to generate a parser.
