### ISSUE TITLE
Jetpack -> Modifiers -> Actions: 	 Modifier.clickable(     enabled: Boolean,     onClickLabel: String?,     role: Role?,     onClick: () -> Unit )

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-jetpack#201]
Doc: https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier#(androidx.compose.ui.Modifier).clickable(kotlin.Boolean,kotlin.String,androidx.compose.ui.semantics.Role,kotlin.Function0)

Configure component to receive clicks via input or accessibility "click" event.

**Comment by nelson-glauber** [comment]
Native usage of `clickable` modifier (it's using just the lambda parameter, the other ones are optional)

```
import androidx.compose.foundation.clickable
import androidx.compose.material.Text
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier

val count = remember { mutableStateOf(0) }
// content that you want to make clickable
Text(text = count.value.toString(), modifier = Modifier.clickable { count.value += 1 })
```

**Comment by bcardarella** [comment]
@nelson-glauber I don't think that modifier would be a valid use-case for us. In this case the `clickable` should trigger a `phx-click` event to allow the server side state to increment the value, update the template render, send the diff to the client.

**Comment by nelson-glauber** [comment]
@bcardarella my question is how we're going to represent this modifier in the stylesheet.
Not sure if I understood your comment, but we can't just simply replace the `clickable` modifier by using the `phx-click` attribute. Because the order of the modifiers matters.
See the example below...
```
Box(
    contentAlignment = Alignment.Center,
    modifier = Modifier
        .size(200.dp)
        .border(2.dp, Color.Red)
        .background(Color.Green)
        .padding(50.dp)
        .clickable {
            // Call the server function
        }
        .background(Color.Yellow),
) {
    Text(
        text = "Hello",
        modifier = modifier
    )
}
```
This is the result:
![Screenshot 2024-04-03 at 12 01 22 PM](https://github.com/liveview-native/liveview-client-jetpack/assets/20464075/3b27d16d-19f1-4c82-a634-6eda2d49155a)
In the example above, just the yellow part is clickable. So, the `clickable` modifier must be declared between two other modifiers.
Currently, this is how I'm assuming that other modifiers would be received by the client:
```
%{"myStyle" => [
    {:size, [], [200]},
    {:border, [], [2, {:., [], [:Color, :Red]}]},
    {:background, [], [{:., [], [:Color, :Green]} ]},
    {:padding, [], [50]},
    // Clickable???
    {:background, [], [{:., [], [:Color, :Yellow]} ]},
]}
```

**Comment by bcardarella** [comment]
Yes but for the example of using `clickable` I would advocate that it should kick off an event similar to what happens in SwiftUI:

```
clickable(event("closeSheet"))
```

But an even bigger question is if we should support this modifier at all. We have the `phx-click` event that we can attach to views in the markup which seems like it would satisfy the same concern.

As far as capturing other lambdas we should probably look at those on a case by case basis to determine if a common pattern could emerge.

**Comment by nelson-glauber** [comment]
Just to have in mind that, as I mentioned earlier, the `clickable` modifier has other parameters...
```kotlin
Box(
    modifier = Modifier
        // other modifiers
        .clickable(
            enabled = true, // You can disable just the disable the clickable action
            onClickLabel = "string", // this is used for accessibility
            role = Role.Button, // this is also used for accessibility
        ) {
            // Call the server function
        }
        // more modifiers
) ...
```

**Comment by carson-katri** [comment]
That clickable modifier could be written like this:

```kotlin
clickable(enabled = true, onClickLabel = "string", role = Role.Button, onClick = event("my-click-event"))
```

Which would call this handler on the server:

```elixir
def handle_event("my-click-event", _params, _socket)
```

The `event` helper supports other arguments, such as `event("name", debounce: 1000, throttle: 5000)`.

> [!NOTE]
> If you're using the Swift client's rules parser, you'll need to write the arguments in the Swift format (`clickable(enabled: true, ...)`). The Kotlin rules parser could be updated to match Kotlin's syntax more closely.

A more complex one like `onKeyPress` would probably be:
```kotlin
onKeyEvent(onKeyEvent = event("handle-keypress"))
```
The modifier would send the `keyEvent` as JSON to the server with that event.

To get a return value from the server, in the `onKeyEvent` modifier you would need to wait for a response from the server for the given event. If the function can't be async you may just have to pick a default that is always returned for this modifier. Or have the result passed as an extra argument to the modifier:

```kotlin
onKeyEvent(onKeyEvent = event("handle-keypress"), propagate = false)
```
