### ISSUE TITLE
JetPack -> Modifiers -> Actions: 	 Modifier.triStateToggleable(     state: ToggleableState,     enabled: Boolean,     role: Role?,     onClick: () -> Unit )

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-jetpack#214]
Doc: https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier#(androidx.compose.ui.Modifier).triStateToggleable(androidx.compose.ui.state.ToggleableState,kotlin.Boolean,androidx.compose.ui.semantics.Role,kotlin.Function0)

Configure component to make it toggleable via input and accessibility events with three states: On, Off and Indeterminate.

**Comment by nelson-glauber** [comment]
How to handle `ToggleableState` (it's just three values: `On`, `Off`, `Indeterminate`)
