### ISSUE TITLE
JetPack -> Modifiers -> Animation: Modifier.animateEnterExit(     enter: EnterTransition,     exit: ExitTransition,     label: String )

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-jetpack#224]
Doc: https://developer.android.com/reference/kotlin/androidx/compose/animation/AnimatedVisibilityScope#(androidx.compose.ui.Modifier).animateEnterExit(androidx.compose.animation.EnterTransition,androidx.compose.animation.ExitTransition,kotlin.String)

[animateEnterExit](https://developer.android.com/reference/kotlin/androidx/compose/animation/AnimatedVisibilityScope#(androidx.compose.ui.Modifier).animateEnterExit(androidx.compose.animation.EnterTransition,androidx.compose.animation.ExitTransition,kotlin.String)) modifier can be used for any direct or indirect children of [AnimatedVisibility](https://developer.android.com/reference/kotlin/androidx/compose/animation/package-summary#AnimatedVisibility(kotlin.Boolean,androidx.compose.ui.Modifier,androidx.compose.animation.EnterTransition,androidx.compose.animation.ExitTransition,kotlin.String,kotlin.Function1)) to create a different enter/exit animation than what's specified in [AnimatedVisibility](https://developer.android.com/reference/kotlin/androidx/compose/animation/package-summary#AnimatedVisibility(kotlin.Boolean,androidx.compose.ui.Modifier,androidx.compose.animation.EnterTransition,androidx.compose.animation.ExitTransition,kotlin.String,kotlin.Function1)).

**Comment by nelson-glauber** [comment]
This implementation will cover the defaults `EnterTransition` and `ExitTransitions`:
-  `EnterTransition`
  - fadeIn
  - scaleIn
  - slideIn
  - slideInHorizontally
  - slideInVertically
  - expandIn
  - expandHorizontally
  - expandVertically,
-  `ExitTransitions` 
  - fadeOut
  - scaleOut
  - slideOut
  - slideOutHorizontally
  - slideOutVertically
  - shrinkOut
  - shrinkHorizontally
  - shrinkVertically,
