### ISSUE TITLE
JetPack -> Modifiers -> Focus: Modifier.onFocusedBoundsChanged(     onPositioned: (LayoutCoordinates?) -> Unit )

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-jetpack#253]
Doc: https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier#(androidx.compose.ui.Modifier).onFocusedBoundsChanged(kotlin.Function1)

Calls [onPositioned](https://developer.android.com/reference/kotlin/androidx/compose/foundation/package-summary#(androidx.compose.ui.Modifier).onFocusedBoundsChanged(kotlin.Function1)) whenever the bounds of the currently-focused area changes.

**Comment by nelson-glauber** [comment]
Need to confirm which information from the `LayoutCoordinates` is going to be sent to the server when the event happens.
