### ISSUE TITLE
JetPack -> Modifiers -> Padding: Modifier.padding(paddingValues: PaddingValues)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-jetpack#269]
Doc: https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier#(androidx.compose.ui.Modifier).padding(androidx.compose.foundation.layout.PaddingValues)

Apply [PaddingValues](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/PaddingValues) to the component as additional space along each edge of the content's left, top, right and bottom.

**Comment by nelson-glauber** [comment]
Confirm whether it makes sense to implement this modifier, since we have the other Modifier.padding overloads
