### ISSUE TITLE
JetPack -> Modifiers -> Size: Modifier.size(size: DpSize)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-jetpack#340]
Doc: https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier#(androidx.compose.ui.Modifier).size(androidx.compose.ui.unit.DpSize)

Declare the preferred size of the content to be exactly [size](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#(androidx.compose.ui.Modifier).size(androidx.compose.ui.unit.DpSize)).

**Comment by nelson-glauber** [comment]
Implemented in #427
